# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec34b6fda7f1fe36ef48fa6efbb2220f03ae9d39a96dede6ee9c91f9f54ae74a3d32ef94c7e541b327ebd02c25ed13a2aa95666830960f8a3baaee11c889b832
  # https://market.mashape.com/andruxnet/random-famous-quotes
  quote_api_key: aaaaaaaaaaaa
    # https://developer.wolframalpha.com/portal/signin.html
    dialogue_api_key: bbbbbbbbbbbb
    twitter_accounts:
        - consumer_key: ccccccccccccc
          consumer_secret: dddddddddddddd
          access_token: eeeeeeeeeeeeeeee
          access_token_secret: fffffffffffffffffff

test:
  secret_key_base: 57cbd8851eb73cf41ad02ce4b327ceee93b21c75eed45b00d45fd9b86d50eb56d982d7093d20c62f2878181f87b9478d9f695102d327999842781a77495758e5
  quote_api_key: aaaaaaaaaaaa
  # https://developer.wolframalpha.com/portal/signin.html
  dialogue_api_key: bbbbbbbbbbbb
  twitter_accounts:
      - consumer_key: ccccccccccccc
        consumer_secret: dddddddddddddd
        access_token: eeeeeeeeeeeeeeee
        access_token_secret: fffffffffffffffffff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  quote_api_key: <%= ENV["QUOTE_API_KEY"] %>
  dialogue_api_key: <%= ENV["WOLFRAM_ALPHA_API_KEY"] %>
  twitter_accounts:
        - consumer_key: <%= ENV["CONSUMER_KEY"] %>
          consumer_secret: <%= ENV["CONSUMER_SECRET"] %>
          access_token: <%= ENV["ACCESS_TOKEN"] %>
          access_token_secret: <%= ENV["ACCESS_TOKEN_SECRET"] %>
